name: GitHub Actions Demo
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      # Setup and Build
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm install
      - name: build package
        run: npm run build
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      # Upload to IPFS:
      # - name: Try to upload built packages to IPFS
      #   if: ${{ job.status == 'success' }}
      #   uses: aquiladev/ipfs-action@v0.1.6
      #   id: ipfs
      #   with:
      #     path: ./build
      #     service: pinata
      #     pinataKey: ${{ secrets.PINATA_API_KEY }}
      #     pinataSecret: ${{ secrets.PINATA_API_SECRET }}

      # Start the Slack Messages:
      # - name: Send custom SUCCESS JSON data to Slack workflow
      #   if: ${{ always() && job.status == 'success' }}
      #   id: slackSuccess
      #   uses: slackapi/slack-github-action@v1.16.0
      #   with:
      #     payload: "{\"message\":\"Github repo: ${{ github.repository }}\\n* Branch: ${{ github.ref }}\\n* Status: 🎉  ${{ job.status }}  🍏\"}"
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      # - name: Send custom FAILURE JSON data to Slack workflow
      #   if: ${{ always() && job.status != 'success' }}
      #   id: slackFailure
      #   uses: slackapi/slack-github-action@v1.16.0
      #   with:
      #     payload: "{\"message\":\"Github repo: ${{ github.repository }}\\n* Branch: ${{ github.ref }}\\n* Status: 🤔  ${{ job.status }}  💣💥\"}" 
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}